workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - build

.build-env-windows: &build-env-windows |
  invoke-webrequest https://static.joinself.com/self-crypto/self-crypto-windows-dependencies.zip -outfile deps.zip
  expand-archive deps.zip .

.build: &build |
  yarn install
  yarn prebuild

build-windows:
  stage: build
  image: eu.gcr.io/principal-oxide-204416/windows-build:fe41b3fef072209298aa6545a22adcf9ddda45b1
  script:
    - *build-env-windows
    - *build
  tags:
    - windows-docker
