workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - build

.build-env-windows: &build-env-windows |
  invoke-webrequest https://static.joinself.com/self-crypto/self-crypto-windows-dependencies.zip -outfile deps.zip
  expand-archive deps.zip .

.build: &build |
  yarn install
  yarn prebuild

build-windows:
  stage: build
  image: eu.gcr.io/principal-oxide-204416/windows-build:bdf2d4626292664995a55c4c43a5873798fcd4a9
  script:
    - 'dir env:'
    - '$env:path'
    - *build-env-windows
    - *build
  tags:
    - windows-docker
